/**
 * 震度別の「交通・ライフラインに何が起きるか」の文言（16言語）。
 *
 * 出典: 気象庁「震度階級関連解説表」（平成21年3月31日改訂）
 *       「ライフライン・インフラ等への影響」
 *       https://www.jma.go.jp/jma/kishou/know/shindo/kaisetsu.html
 *
 * ## 訳出で守っている線
 *
 * - **断定と非断定を原文どおりに保つ。** 原文は一律に「〜ことがある」ではなく
 *   打ち分けられている。断定形（ガスメーターの遮断・エレベーターの自動停止・
 *   伝言サービスの提供・鉄道と高速道路の規制）はいずれも「機器の仕様」か
 *   「事業者の運用ルール」が主語で、非断定形（断水・停電、広域の供給停止、
 *   復旧の遅れ、留意事項）は確率的な結果。訳で "will" 相当に強めない。
 * - **`transit` の限定節を落とさない。** 原文に「各事業者の判断によって」
 *   「基準は、事業者や地域によって異なる」と明示されている。
 *   気象庁の公式英訳はこの限定節を落とす代わりに "may be stopped" と
 *   非断定にして等価を取っているが、ここでは**限定節を残す方を選んだ**ので
 *   動詞は原文どおり断定にしている（16言語すべてで断定）。
 * - **命令形にしない。** この表は現象・被害の記述であって行動指示ではない。
 *   「エレベーターを使わないでください」はアプリ独自の助言で出典が違う。
 * - **「程度以上」の曖昧さ**（"about ... or more"）は閾値側
 *   （lib/intensityImpact.ts）で保っている。厳密なカットオフではない。
 *
 * ## 既知の限界（ネイティブ確認が取れていない箇所）
 *
 * - ne: `सञ्चालक`（事業者）/ `राजमार्ग`（高速道路）は、日本の「高速道路」に対して
 *   一般国道と読まれる余地がある
 * - ne / th の「災害用伝言ダイヤル」は定訳が存在せず逐語的な説明訳
 * - 「地震管制装置」「災害用伝言板」は日本固有の用語で、全言語とも説明訳。
 *   tl のみフィリピンでの英語併用慣行に合わせ英語表記を残している
 * - de の `Erdbebensteuerung` は自然なドイツ語だが業界用語としての定着度は未確認
 *
 * 表示するかどうかの判定は `lib/intensityImpact.ts`。ここは文言だけを持つ。
 */

export const IMPACT_TEXT: Record<string, Record<string, string>> = {
  heading: { ja: 'この揺れで起きること', en: 'What this level of shaking affects', zh: '这种摇晃的影响', 'zh-TW': '這種搖晃的影響', ko: '이 흔들림으로 일어나는 일', vi: 'Ảnh hưởng của rung lắc này', th: 'ผลกระทบจากแรงสั่นระดับนี้', id: 'Dampak guncangan ini', ms: 'Kesan gegaran ini', tl: 'Epekto ng pagyanig na ito', ne: 'यो कम्पनको असर', fr: 'Effets de cette secousse', de: 'Auswirkungen dieser Erschütterung', it: 'Effetti di questa scossa', es: 'Efectos de esta sacudida', easy_ja: 'この ゆれで おきること' },
  transit: { ja: '鉄道や高速道路で、安全確認のため運転見合わせや通行規制が行われます。基準は事業者や地域によって異なります。', en: 'Trains and highways are stopped or restricted for safety checks. Criteria vary by operator and region.', zh: '为确认安全，铁路会停运、高速公路会实施通行管制。标准因运营商和地区而异。', 'zh-TW': '為確認安全，鐵路會停駛、高速公路會實施通行管制。標準因業者和地區而異。', ko: '안전 확인을 위해 철도 운행 중단이나 고속도로 통행 규제가 실시됩니다. 기준은 사업자와 지역에 따라 다릅니다.', vi: 'Đường sắt và đường cao tốc bị dừng hoặc hạn chế lưu thông để kiểm tra an toàn. Tiêu chuẩn khác nhau tùy nhà khai thác và khu vực.', th: 'รถไฟและทางด่วนจะหยุดให้บริการหรือจำกัดการสัญจรเพื่อตรวจสอบความปลอดภัย เกณฑ์แตกต่างกันตามผู้ให้บริการและพื้นที่', id: 'Kereta dan jalan tol dihentikan atau dibatasi untuk pemeriksaan keselamatan. Kriterianya berbeda menurut operator dan wilayah.', ms: 'Kereta api dan lebuh raya dihentikan atau dihadkan untuk pemeriksaan keselamatan. Kriteria berbeza mengikut pengendali dan kawasan.', tl: 'Hinihinto o nililimitahan ang tren at expressway para sa pagsusuri sa kaligtasan. Iba-iba ang pamantayan depende sa operator at lugar.', ne: 'सुरक्षा जाँचका लागि रेल र राजमार्ग रोकिन्छ वा नियन्त्रण गरिन्छ। मापदण्ड सञ्चालक र क्षेत्रअनुसार फरक हुन्छ।', fr: 'Trains et autoroutes sont arrêtés ou soumis à restrictions pour vérification. Les critères varient selon l’exploitant et la région.', de: 'Züge und Autobahnen werden zur Sicherheitsprüfung gestoppt oder gesperrt. Kriterien variieren je nach Betreiber und Region.', it: 'Treni e autostrade vengono fermati o soggetti a limitazioni per controlli di sicurezza. I criteri variano per gestore e zona.', es: 'Los trenes y las autopistas se detienen o se restringen para comprobar la seguridad. Los criterios varían según el operador y la región.', easy_ja: 'あんぜんを たしかめるため、でんしゃが とまります。こうそくどうろも とおれなく なります。きまりは かいしゃや ちいきで ちがいます。' },
  gas: { ja: '安全装置付きのガスメーターが作動し、ガスの供給が止まります。', en: 'Gas meters with safety devices trip, stopping the gas supply.', zh: '带安全装置的燃气表启动，燃气供应中断。', 'zh-TW': '附安全裝置的瓦斯表啟動，瓦斯供應中斷。', ko: '안전장치가 달린 가스미터가 작동하여 가스 공급이 멈춥니다.', vi: 'Đồng hồ gas có thiết bị an toàn kích hoạt và ngắt nguồn gas.', th: 'มิเตอร์แก๊สที่มีอุปกรณ์นิรภัยจะทำงานและตัดการจ่ายแก๊ส', id: 'Meteran gas dengan alat pengaman aktif dan memutus pasokan gas.', ms: 'Meter gas dengan peranti keselamatan berfungsi dan memutuskan bekalan gas.', tl: 'Gumagana ang gas meter na may safety device at nahihinto ang suplay ng gas.', ne: 'सुरक्षा उपकरण भएको ग्यास मिटर चल्छ र ग्यास आपूर्ति रोकिन्छ।', fr: 'Les compteurs de gaz à dispositif de sécurité se déclenchent et coupent le gaz.', de: 'Gaszähler mit Sicherheitsvorrichtung lösen aus und stoppen die Gaszufuhr.', it: 'I contatori del gas con dispositivo di sicurezza scattano e interrompono l’erogazione.', es: 'Los medidores de gas con dispositivo de seguridad se activan y cortan el suministro.', easy_ja: 'あんぜんそうちの ついた ガスメーターが うごいて、ガスが とまります。' },
  utility: { ja: '断水や停電が発生することがあります。', en: 'Suspension of water supply and blackouts may occur.', zh: '可能会发生停水和停电。', 'zh-TW': '可能會發生停水和停電。', ko: '단수나 정전이 발생할 수 있습니다.', vi: 'Có thể xảy ra mất nước và mất điện.', th: 'อาจเกิดน้ำไม่ไหลและไฟดับ', id: 'Pemadaman air dan listrik dapat terjadi.', ms: 'Bekalan air dan elektrik boleh terputus.', tl: 'Maaaring mawalan ng tubig at kuryente.', ne: 'पानी र बिजुली आपूर्ति रोकिन सक्छ।', fr: 'Des coupures d’eau et d’électricité peuvent survenir.', de: 'Wasser- und Stromausfälle können auftreten.', it: 'Possono verificarsi interruzioni di acqua ed elettricità.', es: 'Pueden producirse cortes de agua y de electricidad.', easy_ja: 'みずが でなくなったり、でんきが きえたり することが あります。' },
  elevator: { ja: '地震管制装置付きのエレベーターが自動で停止します。運転再開には時間がかかることがあります。', en: 'Elevators with earthquake control devices stop automatically. Resumption of service may be delayed.', zh: '装有地震管制装置的电梯会自动停止。恢复运行可能需要时间。', 'zh-TW': '裝有地震管制裝置的電梯會自動停止。恢復運行可能需要時間。', ko: '지진 관제 장치가 달린 엘리베이터는 자동으로 멈춥니다. 운행 재개에는 시간이 걸릴 수 있습니다.', vi: 'Thang máy có thiết bị điều khiển động đất tự động dừng lại. Việc hoạt động trở lại có thể mất thời gian.', th: 'ลิฟต์ที่มีระบบควบคุมแผ่นดินไหวจะหยุดอัตโนมัติ การกลับมาใช้งานอาจใช้เวลา', id: 'Lift dengan alat kendali gempa berhenti otomatis. Pengoperasian kembali bisa memakan waktu.', ms: 'Lif dengan peranti kawalan gempa berhenti secara automatik. Operasi semula mungkin mengambil masa.', tl: 'Awtomatikong humihinto ang elevator na may earthquake control device. Maaaring matagalan bago muling gumana.', ne: 'भूकम्प नियन्त्रण उपकरण भएको लिफ्ट स्वतः रोकिन्छ। पुनः सञ्चालन हुन समय लाग्न सक्छ।', fr: 'Les ascenseurs à dispositif sismique s’arrêtent automatiquement. La remise en service peut prendre du temps.', de: 'Aufzüge mit Erdbebensteuerung halten automatisch an. Die Wiederinbetriebnahme kann sich verzögern.', it: 'Gli ascensori con dispositivo antisismico si fermano automaticamente. La ripresa del servizio può richiedere tempo.', es: 'Los ascensores con dispositivo sísmico se detienen automáticamente. La reanudación del servicio puede tardar.', easy_ja: 'じしんの そうちが ついた エレベーターは、じどうで とまります。また うごくまでに じかんが かかることが あります。' },
  messageService: { ja: '通信事業者が災害用伝言ダイヤルや災害用伝言板の提供を行います。', en: 'Telecom providers offer disaster message dial and message board services.', zh: '电信运营商提供灾害用留言电话和灾害用留言板服务。', 'zh-TW': '電信業者提供災害用留言專線和災害用留言板服務。', ko: '통신사업자가 재해용 음성 메시지 다이얼과 재해용 메시지 게시판을 제공합니다.', vi: 'Nhà mạng viễn thông cung cấp tổng đài nhắn tin và bảng nhắn tin dùng khi thảm họa.', th: 'ผู้ให้บริการโทรคมนาคมเปิดบริการสายฝากข้อความและกระดานข้อความสำหรับภัยพิบัติ', id: 'Operator telekomunikasi menyediakan layanan pesan suara dan papan pesan bencana.', ms: 'Pengendali telekom menyediakan perkhidmatan pesanan suara dan papan pesanan bencana.', tl: 'Nagbibigay ang mga telecom provider ng disaster message dial at message board.', ne: 'दूरसञ्चार सेवा प्रदायकले विपद् सन्देश डायल र सन्देश बोर्ड सेवा उपलब्ध गराउँछन्।', fr: 'Les opérateurs télécoms proposent une messagerie vocale et un tableau de messages de catastrophe.', de: 'Telekommunikationsanbieter bieten Katastrophen-Sprachbox und Nachrichtenbrett an.', it: 'Gli operatori telefonici attivano il servizio di messaggi vocali e la bacheca messaggi per le calamità.', es: 'Las operadoras de telecomunicaciones ofrecen el servicio de mensajes de voz y el tablón de mensajes por desastre.', easy_ja: 'でんわの かいしゃが、でんごんダイヤルと でんごんばんを つかえるように します。' },
  widespread: { ja: '広い地域で、ガス・水道・電気の供給が停止することがあります。', en: 'Gas, water and electricity supplies may stop over wide areas.', zh: '大范围地区的燃气、自来水和电力供应可能中断。', 'zh-TW': '大範圍地區的瓦斯、自來水和電力供應可能中斷。', ko: '넓은 지역에서 가스·수도·전기 공급이 멈출 수 있습니다.', vi: 'Nguồn gas, nước và điện có thể ngừng trên diện rộng.', th: 'แก๊ส น้ำประปา และไฟฟ้าอาจหยุดจ่ายเป็นบริเวณกว้าง', id: 'Pasokan gas, air, dan listrik dapat terhenti di wilayah luas.', ms: 'Bekalan gas, air dan elektrik boleh terhenti di kawasan luas.', tl: 'Maaaring mahinto ang suplay ng gas, tubig at kuryente sa malawak na lugar.', ne: 'फराकिलो क्षेत्रमा ग्यास, पानी र बिजुली आपूर्ति रोकिन सक्छ।', fr: 'L’alimentation en gaz, en eau et en électricité peut être coupée sur de vastes zones.', de: 'Gas-, Wasser- und Stromversorgung können großflächig ausfallen.', it: 'Le forniture di gas, acqua ed elettricità possono interrompersi su vaste aree.', es: 'El suministro de gas, agua y electricidad puede interrumpirse en zonas amplias.', easy_ja: 'ひろい ちいきで、ガス・みず・でんきが とまることが あります。' },
  disclaimer: { ja: '同じ震度でも、建物や階によって揺れの強さは異なります。ここに挙げたすべてが起きるとは限らず、被害がこれより大きいことも小さいこともあります。', en: 'Shaking differs by building and by floor. Not all of these occur, and damage may be greater or smaller.', zh: '即使震度相同，摇晃的强度也因建筑和楼层而异。这里列出的不一定都会发生，损害可能比这更大，也可能更小。', 'zh-TW': '即使震度相同，搖晃的強度也因建築和樓層而異。這裡列出的不一定都會發生，災情可能比這更大，也可能更小。', ko: '같은 진도라도 건물과 층에 따라 흔들림의 강도가 다릅니다. 여기 적힌 것이 모두 일어나지는 않으며, 피해가 이보다 클 수도 작을 수도 있습니다.', vi: 'Cùng một cấp độ, độ rung vẫn khác nhau tùy tòa nhà và tầng. Không phải mọi điều nêu trên đều xảy ra, và thiệt hại có thể lớn hơn hoặc nhỏ hơn thế.', th: 'แม้ระดับความสั่นสะเทือนเท่ากัน แรงสั่นก็ต่างกันตามอาคารและชั้น สิ่งที่ระบุไว้อาจไม่เกิดทั้งหมด และความเสียหายอาจมากกว่าหรือน้อยกว่านี้', id: 'Pada tingkat yang sama, guncangan tetap berbeda menurut bangunan dan lantai. Tidak semua hal di atas terjadi, dan kerusakan bisa lebih besar atau lebih kecil dari ini.', ms: 'Pada tahap yang sama, gegaran tetap berbeza mengikut bangunan dan tingkat. Tidak semua di atas berlaku, dan kerosakan boleh lebih besar atau lebih kecil daripada ini.', tl: 'Kahit pareho ang antas, iba-iba ang lakas ng pagyanig sa bawat gusali at palapag. Hindi lahat ng nabanggit ay nangyayari, at maaaring mas malaki o mas maliit ang pinsala.', ne: 'उही स्तरमा पनि भवन र तलाअनुसार कम्पन फरक हुन्छ। यहाँ उल्लेख गरिएका सबै हुँदैनन्, र क्षति यसभन्दा ठूलो वा सानो पनि हुन सक्छ।', fr: 'À intensité égale, les secousses varient selon le bâtiment et l’étage. Tout ne se produit pas, et les dégâts peuvent être plus ou moins importants.', de: 'Bei gleicher Stufe ist die Erschütterung je nach Gebäude und Stockwerk anders. Nicht alles davon tritt ein, und die Schäden können größer oder geringer ausfallen.', it: 'A parità di intensità, la scossa varia per edificio e per piano. Non tutto si verifica e i danni possono essere maggiori o minori.', es: 'Con la misma intensidad, la sacudida varía según el edificio y la planta. No todo ocurre, y los daños pueden ser mayores o menores.', easy_ja: 'おなじ しんどでも、たてものや かいで ゆれかたが ちがいます。ぜんぶが おきるとは かぎりません。ひがいが これより おおきいことも、ちいさいことも あります。' },
};
